Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -46,17 +46,25 @@ jobs:
       - name: Build app
         run: npm run build
 
-      - name: Set S3 bucket based on branch
+      - name: Set S3 bucket based on branch or pull request
         id: set_bucket
         run: |
-          if [ "${{ github.ref_name }}" == "staging" ]; then
+          # Determine branch for pull request or push event
+          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
+            BRANCH_NAME="${{ github.event.pull_request.base.ref }}"
+          else
+            BRANCH_NAME="${{ github.ref_name }}"
+          fi
+
+          # Set S3 bucket based on branch
+          if [[ "$BRANCH_NAME" == "staging" ]]; then
             echo "S3_BUCKET=${{ secrets.AWS_S3_BUCKET_STAGING }}" >> $GITHUB_ENV
             echo "BUCKET_ENVIRONMENT=staging" >> $GITHUB_ENV
-          elif [ "${{ github.ref_name }}" == "production" ]; then
+          elif [[ "$BRANCH_NAME" == "production" ]]; then
             echo "S3_BUCKET=${{ secrets.AWS_S3_BUCKET_PRODUCTION }}" >> $GITHUB_ENV
             echo "BUCKET_ENVIRONMENT=production" >> $GITHUB_ENV
           else
-            echo "Error: Unsupported branch ${GITHUB_REF}" >&2
+            echo "Error: Unsupported branch $BRANCH_NAME" >&2
             exit 1
           fi
 
